# Generated by Django 3.0.6 on 2020-05-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_status',
            field=models.CharField(choices=[('Submitted', 'Claim Submitted'), ('Denied', 'Claim Denied'), ('Approved', 'Claim Approved'), ('Completed', 'Claim Completed')], default='Submitted', max_length=20),
        ),
    ]
