# Generated by Django 3.0.6 on 2020-05-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_claim_claim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='claim_status',
            new_name='status',
        ),
    ]
