# Generated by Django 3.0.6 on 2020-05-28 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200527_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='coverage_end',
            field=models.DateField(default=datetime.date(2021, 5, 28)),
        ),
    ]
