# Generated by Django 3.0.6 on 2020-06-08 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20200603_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='claims/'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverage_end',
            field=models.DateField(default=datetime.date(2021, 6, 8)),
        ),
    ]
