# Generated by Django 3.0.6 on 2020-06-09 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20200608_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverage_end',
            field=models.DateField(default=datetime.date(2021, 6, 9)),
        ),
    ]
