# Generated by Django 3.0.6 on 2020-06-10 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_claimattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='coverage_end',
            field=models.DateField(default=datetime.date(2021, 6, 10)),
        ),
    ]
